name: dive_obslib_example
description: Demonstrates how to use the dive_obslib plugin.
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: '>=3.7.0'

dependencies:
  flutter:
    sdk: flutter

  dive_obslib:
    path: ../

  # From darky12s@gmail.com: a state-manangement library
  flutter_riverpod: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
