name: dive_obslib
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # From Dart team: Utilities for working with FFI code
  ffi: ^1.0.0

  # From: yuli.dev. Simple, fast generation of RFC4122 UUIDs
  uuid: ^2.2.2

dev_dependencies:
  ffigen: ^2.4.2

  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DiveObsLibPlugin
