name: dive_core
description: A new flutter plugin project.
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
author:
homepage:

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

  dive_obslib:
    path: ../dive_obslib

  # From Dart Team: provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.16.1

  # From darky12s@gmail.com: a state-manangement library
  riverpod: ^0.13.1

  # From: yuli.dev. Simple, fast generation of RFC4122 UUIDs
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
