name: dive_core
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # From darky12s@gmail.com: a state-manangement library
  riverpod: ^0.12.1

  # # From dash-overflow.net: reimplements ValueNotifier outside of Flutter
  # state_notifier: ^0.6.0

  # From: yuli.dev. Simple, fast generation of RFC4122 UUIDs
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DiveCorePlugin
