name: example
description: A Dive example.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dive:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
  uses-material-design: true
