name: example
description: A Dive example.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dive:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/image1.jpg
    - assets/image2.jpg
  uses-material-design: true
