name: dive_core_example
description: Demonstrates how to use the dive_core plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dive_core:
    path: ../

  # From dash-overflow.net: a state-manangement library
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
