name: dive_video_source
description: A new flutter plugin project.
version: 0.1.0-alpha.1
homepage: https://divekit.dev

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.8.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dive:
    path: ../dive

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DiveVideoSourcePlugin
