name: dive_obslib
description: A Flutter plugin package for Dive that provides low level access to obslib using FFI.
version: 0.1.0
homepage: https://divekit.dev
repository: https://github.com/larryaasen/dive/tree/main/packages/dive_obslib

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

  # From Dart team: Utilities for working with FFI code
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^4.1.3

  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DiveObsLibPlugin
