# When starting app from Xcode, use attach to connect VS Code to the running
# Flutter app.
attach:
	flutter attach --no-sound-null-safety --target=lib/main.dart --debug-uri http://127.0.0.1:64830/Y82puNvoaBc=/
