name: dive_ui_example
description: Demonstrates how to use the dive_ui plugin.
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: '>=1.22.4'

dependencies:
  flutter:
    sdk: flutter

  # Dive UI
  dive_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
