name: dive_av_example
description: Demonstrates how to use the dive_av plugin.
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dive_av:
    path: ../

  uvc: ^1.2.0

  # uvc_flutter:
  #   path: ../../uvc_flutter

  cupertino_icons: ^1.0.2

  desktop_window: ^0.4.0

  syncfusion_flutter_core: ^25.1.41
  syncfusion_flutter_sliders: ^25.1.41

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
