name: dive_ui
description: The Dive UI widgets. A toolkit for video recording and streaming.
version: 0.1.0
homepage: https://divekit.dev
repository: https://github.com/larryaasen/dive/tree/main/packages/dive_ui

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  dive:
    path: ../dive

  # From bloclibrary.dev: easy to implement the BLoC Design Pattern
  bloc: ^8.1.1

  # From dart.dev: immutable collections using the builder pattern
  built_collection: ^5.1.1

  # From fluttetcommunity.dev: Simplify Dart Equality Comparisons
  equatable: ^2.0.5

  # From flutter.dev: A Flutter plugin that manages files and interactions with file dialogs.
  file_selector: ^0.9.2+4

  # From flutter.dev: The macOS implementation of file_selector.
  file_selector_macos: ^0.9.0+6

  # From bloclibrary.dev: Widgets that make it easy to use blocs and cubits
  flutter_bloc: ^8.1.2
  
  #From: flutter.dev: A Flutter plugin for iOS and Android allowing access to the device cameras.
  # camera: ^0.5.8+10

  # From darky12s@gmail.com: a state-manangement library
  flutter_riverpod: ^2.3.1

  # From Dart Team: provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # From Dart team:
  path: ^1.8.2

  # From Dart team:
  path_provider: ^2.0.13

  # From flutter.dev: Flutter plugin for playing back video on a Widget surface.
  # video_player: '>=0.10.12+3 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
