name: dive_av
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/larryaasen/dive
repository: https://github.com/larryaasen/dive/tree/main/packages/dive_av

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: DiveAVPlugin
