name: dive
description: The Dive core plugin. A toolkit for video recording and streaming.
version: 0.7.0
homepage: https://divekit.dev
repository: https://github.com/larryaasen/dive/tree/main/packages/dive

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0

  dive_obslib: ^0.5.0

  # From fluttetcommunity.dev: Simplify Dart Equality Comparisons
  equatable: ^2.0.5

  # From Dart Team: provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.17.0

  # From darky12s@gmail.com: a state-manangement library
  riverpod: ^2.3.1

  # From: yuli.dev. Simple, fast generation of RFC4122 UUIDs
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
